baseURL = "https://schrmm.github.io/"
languageCode = "en-us"
title = "Portfolio"
enableRobotsTXT = true

# Site parameters
[params]
  author = "Jane Doe"
  description = "Personal portfolio site powered by Hugo"
  
  [params.social]
    github = "https://github.com/schrmm"
    linkedin = "https://linkedin.com/in/janedoe"

# Menu items
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume/"
    weight = 3
