name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          # Build the site with Hugo
          hugo --minify
          
          # Debug: List the public directory contents
          echo "Public directory contents:"
          find public -type f | sort
          
          # Ensure index.html is in the root
          cat > public/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Portfolio</title>
              <script src="https://cdn.tailwindcss.com"></script>
          </head>
          <body class="bg-gray-50">
              <header class="bg-white shadow-md">
                  <nav class="max-w-6xl mx-auto px-4 py-4">
                      <div class="flex justify-between items-center">
                          <a href="/" class="text-xl font-bold text-blue-600">Jane Doe</a>
                          <div class="flex space-x-6">
                              <a href="/" class="text-gray-700 hover:text-blue-600">Home</a>
                              <a href="/projects/" class="text-gray-700 hover:text-blue-600">Projects</a>
                              <a href="/resume/" class="text-gray-700 hover:text-blue-600">Resume</a>
                          </div>
                      </div>
                  </nav>
              </header>

              <main>
                  <!-- Hero Section -->
                  <section class="py-20 bg-gradient-to-r from-blue-500 to-indigo-600 text-white">
                      <div class="max-w-6xl mx-auto px-4 text-center">
                          <h1 class="text-4xl md:text-6xl font-bold mb-2">Jane Doe</h1>
                          <p class="text-xl max-w-3xl mx-auto mb-8">Welcome to my portfolio website</p>
                      </div>
                  </section>

                  <!-- Content Section -->
                  <section class="py-16 bg-white">
                      <div class="max-w-6xl mx-auto px-4">
                          <h2 class="text-3xl font-bold mb-8 text-center">About This Site</h2>
                          <p class="text-center text-gray-700">
                              This is a portfolio site built with Hugo and deployed to GitHub Pages.
                          </p>
                      </div>
                  </section>
              </main>

              <footer class="py-8 bg-gray-800 text-gray-300">
                  <div class="max-w-6xl mx-auto px-4 text-center">
                      <p>© 2025 Jane Doe - All Rights Reserved</p>
                  </div>
              </footer>
          </body>
          </html>
          EOF
          
          # Verify the index.html file exists
          ls -la public/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
