name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: |
          # Build the site with Hugo
          hugo --minify
          
          # Debug: List the public directory contents
          echo "Public directory contents:"
          find public -type f | sort
          
          # Make sure the projects and resume directories exist
          mkdir -p public/projects
          mkdir -p public/resume
          
          # Verify the directories and index files
          ls -la public
          ls -la public/projects
          ls -la public/resume

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
